### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by azylman** [mozilla-services/logstash-metlog#12]
In several places, you guys link to https://github.com/mozilla-services/vagrant-metlog-backend/blob/master/files/logstash.conf for an example configuration

This link 404s.

Places that I've found that link to it:

http://logstash-metlog.readthedocs.org/en/latest/config.html
https://wiki.mozilla.org/CloudServices/Sagrada/Metlog#Setting_up_Metlog_with_Logstash

I'd love it if this was fixed - I'm trying to get this set up, so an example would be great.

**Comment by rafrombrc** [comment]
Urgh. All of this is deprecated. We no longer use "metlog" nor logstash at all, that's all been replaced by Heka (https://github.com/mozilla-services/heka).

You're welcome to wrestle with it, but I'm afraid we won't be able to support it at all.

**Comment by azylman** [comment]
Sounds like this just gives me an opportunity to try out Heka. ;)

Thanks!
